version: '3.5'

services:
  server:
    image: node:12
    volumes:
      - ./:/usr/src/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    working_dir: /usr/src/app
    entrypoint: make setup build serve